server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: oauthservice
          uri: http://localhost:8081
          predicates:
            - Path=/oauth/**
        - id: userservice
          uri: http://localhost:8090
          predicates:
            - Path=/v1/users/**